# Generated by Django 4.2.4 on 2023-10-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='absolute_ban',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='profile_images/profile_image_default.jpg', upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status_ban',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_about',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
