# Generated by Django 4.2.4 on 2023-10-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_status_ban_customuser_usual_ban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/profile_image_default.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
